### ISSUE TITLE
Initialize project structure, dependencies, and basic server setup

### ISSUE THREAD

**Issue by TKanX** [tridecco/game-server#1]
Establish the initial project structure for the backend server repository, install necessary dependencies, and perform basic server setup. This lays the foundation for subsequent development work.

**Comment by TKanX** [comment]
This feature has been fully implemented and tested in commit https://github.com/tridecco/game-server/commit/b997a92fb2f23e671176ae72687fee602e3d4565.

**Comment by tedhyu** [comment]
Good job Tony
