### ISSUE TITLE
Migrate session storage from session-file-store to connect-mongo

### ISSUE THREAD

**Issue by TKanX** [tridecco/game-server#4]
- Installed necessary dependencies: connect-mongo and mongoose.
- Updated configuration files to support MongoDB connection settings.
- Updated session middleware to use MongoStore from connect-mongo.

**Comment by TKanX** [comment]
This chore has been completed and verified in commit https://github.com/tridecco/game-server/commit/3007274d0a68b4f507a5c29ecbc92a4900e1562e.

**Comment by tedhyu** [comment]
Good job!
